# Generated by Django 3.1.5 on 2021-01-13 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0004_auto_20210113_2225'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
